<x-app-layout>
    <x-slot name="header">
        <div class="glass-card overflow-hidden p-0">
            <div class="bg-gradient-to-r from-emerald-900 via-emerald-800 to-teal-700 px-6 py-6 text-white sm:px-8">
                <p class="text-xs uppercase tracking-[0.2em] text-emerald-100">Nutrition &amp; Wellness Hub</p>
                <h2 class="mt-2 text-2xl font-bold sm:text-3xl">Nutrition System Dashboard</h2>
                @if($role !== 'patient')
                    <p class="mt-1 text-sm text-emerald-100/90">Role: {{ ucfirst($role) }}</p>
                @endif
            </div>
            <div class="px-6 py-4 text-sm text-emerald-800 sm:px-8">
                Snapshot of your operational metrics and adherence performance.
            </div>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="section-shell">
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                @php
                    $statHints = [
                        'budget_spent' => 'Total amount spent on your logged meals for the selected period.',
                        'adherence_rate' => 'Percentage of logged meals that match your generated meal plan.',
                        'calories_logged' => 'Total calories from all meals you have logged.',
                        'meals_logged' => 'Number of meals entered into Meal Logs.',
                        'plans_generated' => 'Total meal plans generated by the system.',
                        'active_patients' => 'Patients currently under monitoring and follow-up.',
                        'foods_count' => 'Available food items in the nutrition database.',
                        'guidelines_count' => 'Clinical guideline rules currently active in the system.',
                    ];
                @endphp

                @foreach($stats as $label => $value)
                    @php
                        $normalizedLabel = (string) str($label)->snake();
                    @endphp
                    <div class="stat-card stat-card-hover group cursor-default transform-gpu transition duration-200 hover:shadow-2xl">
                        <p class="text-xs uppercase tracking-[0.2em] text-emerald-700">
                            {{ str($label)->headline() }}
                            @if($normalizedLabel === 'budget_spent')
                                <span class="ml-1 text-emerald-950 opacity-0 transition-opacity duration-200 group-hover:opacity-100">Kshs</span>
                            @endif
                        </p>
                        <p class="mt-3 text-3xl font-bold text-emerald-950">{{ is_numeric($value) ? number_format($value) : $value }}</p>

                        @if($normalizedLabel !== 'budget_spent' && isset($statHints[$normalizedLabel]))
                            <div class="pointer-events-none absolute inset-x-4 bottom-4 translate-y-2 rounded-xl border border-emerald-200 bg-white/95 px-3 py-2 text-[11px] text-emerald-800 opacity-0 shadow-md backdrop-blur-sm transition duration-200 group-hover:translate-y-0 group-hover:opacity-100">
                                {{ $statHints[$normalizedLabel] }}
                            </div>
                        @endif
                    </div>
                @endforeach
            </div>

            <div class="mt-6 simple-chart" data-simple-chart data-labels='@json($chartLabels ?? [])' data-values='@json($chartValues ?? [])'>
                <p class="text-xs uppercase tracking-[0.15em] text-emerald-700">Insights</p>
                <h3 class="mt-2 text-lg font-bold text-emerald-900">{{ $chartTitle ?? 'Performance Trend' }}</h3>
                <div class="mt-4 simple-chart-grid" data-chart-grid></div>
            </div>

            <div class="mt-6 stat-card stat-card-hover group cursor-default transform-gpu p-6 transition duration-200 hover:shadow-2xl">
                @if($role === 'patient')
                    <p class="text-sm text-emerald-800" data-word-flow>Unlock personalized nutrition insights by maintaining your health profile and meal records. Monitor adherence trends, identify nutritional gaps, manage your budget and receive tailored recommendations to support your long-term wellness goals.</p>
                @elseif($role === 'nutritionist')
                    <p class="text-sm text-emerald-800">Monitor patient adherence and prioritize high-risk conditions for weekly review.</p>
                @else
                    <p class="text-sm text-emerald-800">Manage master data quality for food items, clinical rules, and overall platform operations.</p>
                @endif
            </div>

            @if($role === 'patient')
                <div class="mt-8 grid gap-6 xl:grid-cols-12">
                    <section class="glass-card p-6 xl:col-span-8">
                        <div class="flex flex-wrap items-center justify-between gap-3">
                            <h3 class="section-title">Today's Meal Plan</h3>
                            <a href="{{ route('meal-plans.index') }}" class="brand-btn-secondary">View Full Plan</a>
                        </div>
                        <p class="section-subtitle">Track breakfast, lunch, snack, and dinner with quick actions.</p>

                        <div class="mt-5 grid gap-4 sm:grid-cols-2">
                            @foreach(($todayMealPlan ?? []) as $meal)
                                <article class="stat-card stat-card-hover p-4">
                                    <div class="flex items-center justify-between">
                                        <h4 class="text-base font-bold text-emerald-950">{{ $meal['title'] ?? 'Meal' }}</h4>
                                        @if(!empty($meal['is_logged']))
                                            <span class="rounded-full bg-emerald-100 px-2 py-1 text-[11px] font-semibold text-emerald-800">Logged</span>
                                        @endif
                                    </div>

                                    <p class="mt-2 text-sm font-semibold text-emerald-900">{{ $meal['food_name'] ?? 'No meal assigned' }}</p>
                                    <p class="mt-2 text-xs text-emerald-800">Estimated Cost: KES {{ number_format((float) ($meal['cost'] ?? 0), 2) }}</p>
                                    <p class="mt-1 text-xs text-emerald-800">Calories: {{ number_format((float) ($meal['calories'] ?? 0)) }}</p>
                                    <p class="mt-1 text-xs text-emerald-800">Protein/Carbs/Fats: {{ number_format((float) ($meal['protein_g'] ?? 0), 1) }}g / {{ number_format((float) ($meal['carbs_g'] ?? 0), 1) }}g / {{ number_format((float) ($meal['fats_g'] ?? 0), 1) }}g</p>

                                    <div class="mt-3 flex flex-wrap gap-2">
                                        @if(!empty($meal['food_id']) && !empty($meal['has_plan']))
                                            <form method="POST" action="{{ route('meal-logs.quick-store') }}">
                                                @csrf
                                                <input type="hidden" name="food_id" value="{{ $meal['food_id'] }}">
                                                <input type="hidden" name="meal_type" value="{{ $meal['meal_type'] }}">
                                                <input type="hidden" name="quantity" value="{{ $meal['quantity'] }}">
                                                <input type="hidden" name="consumed_on" value="{{ now()->toDateString() }}">
                                                <button type="submit" class="brand-btn">Mark as Eaten</button>
                                            </form>
                                        @else
                                            <button type="button" class="brand-btn opacity-60" disabled>Mark as Eaten</button>
                                        @endif
                                        <a href="{{ route('meal-plans.index') }}" class="brand-btn-secondary">Replace Meal</a>
                                    </div>
                                </article>
                            @endforeach
                        </div>
                    </section>

                    <section class="glass-card p-6 xl:col-span-4">
                        <h3 class="section-title">Meal Logging Quick Action</h3>
                        <p class="section-subtitle">Log meals instantly to keep your progress accurate.</p>
                        <a href="{{ route('meal-logs.index') }}" class="mt-5 inline-flex w-full items-center justify-center rounded-2xl bg-emerald-700 px-5 py-4 text-lg font-bold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-emerald-800">
                            Log Meal
                        </a>
                    </section>
                </div>

                <div class="mt-6 grid gap-6 lg:grid-cols-2">
                    <section class="glass-card p-6">
                        <h3 class="section-title">Nutrition Insights</h3>
                        <ul class="mt-4 space-y-2 text-sm text-emerald-900">
                            @foreach(($nutritionInsights ?? []) as $insight)
                                <li class="rounded-xl border border-emerald-100 bg-white/70 px-3 py-2">{{ $insight }}</li>
                            @endforeach
                        </ul>
                    </section>

                    <section class="glass-card p-6">
                        <h3 class="section-title">Adherence Performance</h3>
                        <div class="mt-4 space-y-3">
                            <div>
                                <p class="text-xs font-semibold uppercase tracking-[0.1em] text-emerald-700">Daily Adherence</p>
                                <div class="mt-1 h-2.5 rounded-full bg-emerald-100">
                                    <div class="h-2.5 rounded-full bg-emerald-600" style="width: {{ (int) ($adherencePerformance['daily'] ?? 0) }}%"></div>
                                </div>
                                <p class="mt-1 text-xs text-emerald-800">{{ (int) ($adherencePerformance['daily'] ?? 0) }}%</p>
                                <p class="text-[11px] text-emerald-700">{{ (int) ($adherencePerformance['dailyFollowed'] ?? 0) }}/{{ (int) ($adherencePerformance['dailyExpected'] ?? 0) }} meals due</p>
                            </div>
                            <div>
                                <p class="text-xs font-semibold uppercase tracking-[0.1em] text-emerald-700">Weekly Adherence</p>
                                <div class="mt-1 h-2.5 rounded-full bg-emerald-100">
                                    <div class="h-2.5 rounded-full bg-emerald-600" style="width: {{ (int) ($adherencePerformance['weekly'] ?? 0) }}%"></div>
                                </div>
                                <p class="mt-1 text-xs text-emerald-800">{{ (int) ($adherencePerformance['weekly'] ?? 0) }}%</p>
                                <p class="text-[11px] text-emerald-700">{{ (int) ($adherencePerformance['weeklyFollowed'] ?? 0) }}/{{ (int) ($adherencePerformance['weeklyExpected'] ?? 0) }} meals due</p>
                            </div>
                            <div>
                                <p class="text-xs font-semibold uppercase tracking-[0.1em] text-emerald-700">Monthly Adherence</p>
                                <div class="mt-1 h-2.5 rounded-full bg-emerald-100">
                                    <div class="h-2.5 rounded-full bg-emerald-600" style="width: {{ (int) ($adherencePerformance['monthly'] ?? 0) }}%"></div>
                                </div>
                                <p class="mt-1 text-xs text-emerald-800">{{ (int) ($adherencePerformance['monthly'] ?? 0) }}%</p>
                                <p class="text-[11px] text-emerald-700">{{ (int) ($adherencePerformance['monthlyFollowed'] ?? 0) }}/{{ (int) ($adherencePerformance['monthlyExpected'] ?? 0) }} meals due</p>
                            </div>
                        </div>

                        <div class="mt-4 grid gap-3 sm:grid-cols-3">
                            <div class="rounded-xl border border-emerald-100 bg-white/70 p-3 text-center">
                                <p class="text-xs text-emerald-700">Meals Followed</p>
                                <p class="text-lg font-bold text-emerald-950">{{ (int) ($adherencePerformance['followed'] ?? 0) }}</p>
                            </div>
                            <div class="rounded-xl border border-emerald-100 bg-white/70 p-3 text-center">
                                <p class="text-xs text-emerald-700">Meals Missed</p>
                                <p class="text-lg font-bold text-emerald-950">{{ (int) ($adherencePerformance['missed'] ?? 0) }}</p>
                            </div>
                            <div class="rounded-xl border border-emerald-100 bg-white/70 p-3 text-center">
                                <p class="text-xs text-emerald-700">Days Completed</p>
                                <p class="text-lg font-bold text-emerald-950">{{ (int) ($adherencePerformance['daysCompleted'] ?? 0) }}</p>
                            </div>
                        </div>
                    </section>
                </div>

                <div class="mt-6 grid gap-6 lg:grid-cols-2">
                    <section class="glass-card p-6">
                        <h3 class="section-title">Budget Tracker</h3>
                        <div class="mt-4 space-y-2 text-sm text-emerald-900">
                            <p>Budget: KES {{ number_format((float) ($budgetTracker['weeklyBudget'] ?? 0), 2) }}</p>
                            <p>Spent: KES {{ number_format((float) ($budgetTracker['spent'] ?? 0), 2) }}</p>
                            <p>Remaining: KES {{ number_format((float) ($budgetTracker['remaining'] ?? 0), 2) }}</p>
                        </div>
                    </section>

                    <section class="glass-card p-6">
                        <h3 class="section-title">Health Goals Progress</h3>
                        <div class="mt-4 space-y-3">
                            @foreach(($healthGoals ?? []) as $goal)
                                <div>
                                    <div class="flex items-center justify-between">
                                        <p class="text-sm font-semibold text-emerald-900">{{ $goal['title'] }}</p>
                                        <p class="text-xs text-emerald-800">{{ (int) $goal['progress'] }}%</p>
                                    </div>
                                    <div class="mt-1 h-2.5 rounded-full bg-emerald-100">
                                        <div class="h-2.5 rounded-full bg-emerald-600" style="width: {{ (int) $goal['progress'] }}%"></div>
                                    </div>
                                    <p class="mt-1 text-xs text-emerald-700">{{ $goal['note'] }}</p>
                                </div>
                            @endforeach
                        </div>
                    </section>
                </div>

                <div class="mt-6 grid gap-6 lg:grid-cols-2">
                    <section class="glass-card p-6">
                        <h3 class="section-title">Personalized Recommendations</h3>
                        <ul class="mt-4 space-y-2 text-sm text-emerald-900">
                            @foreach(($personalizedRecommendations ?? []) as $item)
                                <li class="rounded-xl border border-emerald-100 bg-white/70 px-3 py-2">{{ $item }}</li>
                            @endforeach
                        </ul>
                    </section>

                    <section class="glass-card p-6">
                        <h3 class="section-title">Notifications &amp; Reminders</h3>
                        <ul class="mt-4 space-y-2 text-sm text-emerald-900">
                            @foreach(($notifications ?? []) as $item)
                                <li class="rounded-xl border border-emerald-100 bg-white/70 px-3 py-2">{{ $item }}</li>
                            @endforeach
                        </ul>
                    </section>
                </div>

                <section class="mt-6 glass-card p-6">
                    <h3 class="section-title">Health Trends</h3>
                    <div class="mt-4 grid gap-4 lg:grid-cols-3">
                        <div class="simple-chart" data-simple-chart data-labels='@json($trendLabels ?? [])' data-values='@json($adherenceTrend ?? [])'>
                            <p class="text-xs uppercase tracking-[0.15em] text-emerald-700">Adherence Trend</p>
                            <h4 class="mt-1 text-sm font-bold text-emerald-900">Daily Adherence %</h4>
                            <div class="mt-3 simple-chart-grid" data-chart-grid></div>
                        </div>
                        <div class="simple-chart" data-simple-chart data-labels='@json($trendLabels ?? [])' data-values='@json($budgetTrend ?? [])'>
                            <p class="text-xs uppercase tracking-[0.15em] text-emerald-700">Budget Trend</p>
                            <h4 class="mt-1 text-sm font-bold text-emerald-900">Cumulative Weekly Spend</h4>
                            <div class="mt-3 simple-chart-grid" data-chart-grid></div>
                        </div>
                        <div class="simple-chart" data-simple-chart data-labels='@json($trendLabels ?? [])' data-values='@json($calorieTrend ?? [])'>
                            <p class="text-xs uppercase tracking-[0.15em] text-emerald-700">Calorie Trend</p>
                            <h4 class="mt-1 text-sm font-bold text-emerald-900">Daily Calories</h4>
                            <div class="mt-3 simple-chart-grid" data-chart-grid></div>
                        </div>
                    </div>
                </section>

                <section class="mt-6 glass-card p-6">
                    <h3 class="section-title">Emergency / Support</h3>
                    <div class="mt-4 flex flex-wrap gap-3">
                        <a href="{{ route('patient.help.contact') }}" class="brand-btn-secondary">Contact Nutritionist</a>
                        <a href="{{ route('patient.help.contact') }}" class="brand-btn-secondary">Help Center</a>
                        <a href="{{ route('patient.help.how-to-use') }}" class="brand-btn-secondary">Educational Resources</a>
                    </div>
                </section>
            @endif

        </div>
    </div>
</x-app-layout>
